name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.15.2'
          host: 'linux'
          target: 'android'
          arch: 'android'

      - name: Install SDK
        run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install 'platforms;android-28' 'build-tools;28.0.3' 'ndk;21.3.6528147'

      - name: Build Android package
        working-directory: Desktop_Interface
        run: |
          export ANDROID_NDK_ROOT="${ANDROID_SDK_ROOT}/ndk/21.3.6528147"
          qmake
          make -j$(nproc)
          make INSTALL_ROOT=labrador install
          JAVA_HOME=${JAVA_HOME_11_X64} androiddeployqt --input android-Labrador-deployment-settings.json --output labrador --verbose --gradle --android-platform android-28

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: Desktop_Interface/labrador/build/outputs/apk/debug/labrador-debug.apk
          compression-level: 0
          if-no-files-found: error
