name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and build AppImage
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y build-essential libfftw3-dev qt5-default libusb-1.0-0-dev wget
          cd Desktop_Interface
          ./make_appimage

      - name: Run uploadtool for Linux
        run: |
          export UPLOADTOOL_SUFFIX="Linux"
          find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
          export UPLOADTOOL_BODY="EspoTek Labrador software for Linux. This should be compatible with all modern 64-bit distros. If you're running 32-bit Linux, please see the wiki for build instructions. https://github.com/espotek-org/Labrador/wiki/Building-for-32-bit-Linux"
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh EspoTek_Labrador*.AppImage
