name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y build-essential libfftw3-dev qt5-default libusb-1.0-0-dev wget

      - name: Build AppImage
        working-directory: ./Desktop_Interface
        run: |
          ./make_appimage

      - name: Run uploadtool for Linux
        if: github.ref == 'refs/heads/master'
        working-directory: ./Desktop_Interface
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_SUFFIX: 'Linux'
          UPLOADTOOL_BODY: "EspoTek Labrador software for Linux. This should be compatible with all modern 64-bit distros. If you're running 32-bit Linux, please see the wiki for build instructions. https://github.com/espotek-org/Labrador/wiki/Building-for-32-bit-Linux"
        run: |
          wget -N https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh EspoTek_Labrador*.AppImage
