name: Build macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Homebrew dependencies
        run: |
          brew update
          brew remove --force $(brew list --formula) || true
          brew install fftw libomp qt5 libusb wget
          brew link qt5 --force

      - name: Build macOS app
        working-directory: ./Desktop_Interface
        run: |
          GIT_HASH_SHORT=$(git rev-parse --short HEAD)
          qmake CONFIG+=release PREFIX=/usr DEFINES+=GIT_HASH_SHORT=$GIT_HASH_SHORT
          make -j$(sysctl -n hw.ncpu)
          mkdir -p bin/Labrador.app/Contents/MacOS/Resources
          mkdir -p bin/Labrador.app/Contents/Frameworks
          cp -r bin/firmware bin/Labrador.app/Contents/MacOS
          cp -r bin/waveforms bin/Labrador.app/Contents/MacOS
          cp resources/iconfile.icns bin/Labrador.app/Contents/Resources
          cp resources/Info.plist bin/Labrador.app/Contents
          macdeployqt bin/Labrador.app -dmg -libpath=build_mac/libdfuprog/lib/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: Desktop_Interface/bin/Labrador.dmg
          compression-level: 0
          if-no-files-found: error

  release:
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List artifacts
        run: |
          ls -alR

      - name: Run uploadtool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOADTOOL_ISPRERELEASE: 'true'
          UPLOADTOOL_SUFFIX: 'macOS'
          UPLOADTOOL_BODY: "EspoTek Labrador software for macOS 10.13 and later. If you are running an older version of macOS, please use the macOS Legacy build below."
        run: |
          wget -N https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh Labrador.dmg
