name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-2019
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Download additional files
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "http://espotek.com/ai167.msi" -OutFile "ai167.msi"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/Labrador.aip" -OutFile "Labrador.aip"
          mkdir "driver"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Bootloader_Install.exe" -OutFile "driver/Bootloader_Install.exe"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Driver_Install.exe" -OutFile "driver/Driver_Install.exe"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Gobindar_Install.exe" -OutFile "driver/Gobindar_Install.exe"
          mkdir "Prerequisites/Visual C++ Redistributable for Visual Studio 2017"
          # XXX: Replacing these installers with the 2019 versions and hoping Advanced Installer handles them properly
          #Invoke-WebRequest -Uri "http://download.visualstudio.microsoft.com/download/pr/9fbed7c7-7012-4cc0-a0a3-a541f51981b5/e7eec15278b4473e26d7e32cef53a34c/vc_redist.x64.exe" -OutFile "Prerequisites/Visual C++ Redistributable for Visual Studio 2017/vc_redist.x64.exe"
          #Invoke-WebRequest -Uri "http://download.visualstudio.microsoft.com/download/pr/d0b808a8-aa78-4250-8e54-49b8c23f7328/9c5e6532055786367ee61aafb3313c95/vc_redist.x86.exe" -OutFile "Prerequisites/Visual C++ Redistributable for Visual Studio 2017/vc_redist.x86.exe"
          mv "bin64/vc_redist.x64.exe" "Prerequisites/Visual C++ Redistributable for Visual Studio 2017"
          mv "bin32/vc_redist.x86.exe" "Prerequisites/Visual C++ Redistributable for Visual Studio 2017"

      - name: Install Advanced Installer
        shell: cmd
        run: |
          msiexec /i ai167.msi /qn
          rm ai167.msi

      - name: Register Advanced Installer
        env:
          AI_KEY: ${{ secrets.AI_KEY }}
        if: env.AI_KEY != ''
        shell: cmd
        run: |
          "C:/Program Files (x86)/Caphyon/Advanced Installer 16.7/bin/x86/AdvancedInstaller.com" /register %AI_KEY%

      - name: Build installer
        shell: cmd
        run: |
          "C:/Program Files (x86)/Caphyon/Advanced Installer 16.7/bin/x86/AdvancedInstaller.com" /rebuild Labrador.aip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: Labrador-SetupFiles/Labrador_Installer.exe
          compression-level: 0
          if-no-files-found: error
