name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-2019
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Download additional files
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "http://espotek.com/ai167.msi" -OutFile "ai167.msi"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/Labrador.aip" -OutFile "Labrador.aip"
          mkdir "driver"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Bootloader_Install.exe" -OutFile "driver/Bootloader_Install.exe"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Driver_Install.exe" -OutFile "driver/Driver_Install.exe"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Gobindar_Install.exe" -OutFile "driver/Gobindar_Install.exe"

      - name: Install Advanced Installer
        shell: cmd
        run: |
          msiexec /i ai167.msi /qn
          rm ai167.msi

      - name: Register Advanced Installer
        env:
          AI_KEY: ${{ secrets.AI_KEY }}
        if: env.AI_KEY != ''
        shell: cmd
        run: |
          "C:/Program Files (x86)/Caphyon/Advanced Installer 16.7/bin/x86/AdvancedInstaller.com" /register %AI_KEY%

      - name: Build installer
        shell: cmd
        run: |
          "C:/Program Files (x86)/Caphyon/Advanced Installer 16.7/bin/x86/AdvancedInstaller.com" /rebuild Labrador.aip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: Labrador-SetupFiles/Labrador_Installer.exe
          compression-level: 0
          if-no-files-found: error
