name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - QT_ARCH: 'win64_msvc2019_64'
            PLATFORM: 'x64'
            PLATFORM_ALT_NAME: 'amd64'
            OUTPUT_BIN_DIR: 'bin64'
          - QT_ARCH: 'win32_msvc2019'
            PLATFORM: 'x86'
            PLATFORM_ALT_NAME: 'x86'
            OUTPUT_BIN_DIR: 'bin32'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install eigen
        shell: cmd
        run: |
          choco install eigen

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: '${{ matrix.QT_ARCH }}'

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.PLATFORM }}

      - name: Build Labrador
        working-directory: Desktop_Interface
        shell: cmd
        run: |
          qmake CONFIG+=release INCLUDEPATH+="C:\ProgramData\chocolatey\lib\eigen\include\eigen3"
          nmake

      - name: Gather dependencies
        working-directory: Desktop_Interface
        shell: cmd
        run: |
          windeployqt bin\Labrador.exe
          xcopy /i /s /y "build_win\fftw\${{ matrix.PLATFORM }}"\libfftw3-3.dll bin
          xcopy /i /s /y "build_win\libusbk\bin\dll\${{ matrix.PLATFORM_ALT_NAME }}"\libusbK.dll bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.OUTPUT_BIN_DIR }}
          path: Desktop_Interface/bin

  build-installer:
    needs:
      - build-windows
    runs-on: windows-2019
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Download additional files
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "http://espotek.com/ai167.msi" -OutFile "ai167.msi"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/Labrador.aip" -OutFile "Labrador.aip"
          mkdir "driver"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Bootloader_Install.exe" -OutFile "driver/Bootloader_Install.exe"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Driver_Install.exe" -OutFile "driver/Driver_Install.exe"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Desktop_Interface/build_win/driver/Gobindar_Install.exe" -OutFile "driver/Gobindar_Install.exe"

      - name: Install Advanced Installer
        shell: cmd
        run: |
          msiexec /i ai167.msi /qn
          rm ai167.msi

      - name: Register Advanced Installer
        env:
          AI_KEY: ${{ secrets.AI_KEY }}
        if: env.AI_KEY != ''
        shell: cmd
        run: |
          "C:/Program Files (x86)/Caphyon/Advanced Installer 16.7/bin/x86/AdvancedInstaller.com" /register %AI_KEY%

      - name: Build installer
        shell: cmd
        env:
            PACKAGE_VERSION: "1.0.${{ github.run_number }}"
        run: |
          "C:\Program Files (x86)\Caphyon\Advanced Installer 16.7\bin\x86\AdvancedInstaller.com" /SetVersion %PACKAGE_VERSION% /rebuild Labrador.aip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: Labrador-SetupFiles/Labrador_Installer.exe
          compression-level: 0
          if-no-files-found: error
